# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f01f4942465fb0e25aeb49fd493ccdf9e79acca568e23258af165ce29f487f2dc16c84122e4d709da2ea414a40c3514b63627c767438124767d7424dcf810f8e

test:
  secret_key_base: 7fe71ff3b97823fb92f1efcf778f0c9c7780eb05fe56954ccddf3aced4a7538dc3d02b0aaea5a4d77bb3509716ecaaff63efaf5c80fe80cca967f28a29331b20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
